### ISSUE TITLE
Recommended cDAQ Cards

### ISSUE THREAD

**Issue by kgrammatis** [sandialabs/rattlesnake-vibration-controller#2]
Hi -

Thanks for the great instruction manual! One question I was left with was what is your recommended cDAQ setup for driving accels, sending out the signal to the vibe table, and also reading back in that sent signal (p.25)? There are numerous choices out and I would love to duplicate your cDAQ setup for simplicity.

Thank you!

**Comment by dprohe** [comment]
We've successfully used Rattlesnake with this cDAQ configuration
- NI cDAQ 9174
- NI 9263 (Analog Output +/-10V)
- NI 9215 (Analog Input +/-10V)
- NI 9234 (IEPE +/-5V AC/DC)

I can't say I recommend it because I haven't tried other configurations that might be better or worse.  But Rattlesnake should be able to use any NI-DAQmx-compatible devices.

**Comment by kgrammatis** [comment]
Thank you. I'm going to track these down.
