### ISSUE TITLE
Creating Environments Without Matlab or Numpy

### ISSUE THREAD

**Issue by kgrammatis** [sandialabs/rattlesnake-vibration-controller#3]
On page 64 of your documentation you describe that a spectral density using Matlab or Numpy. Are there other ways to do this for simple spectral densities? An example spectra is detailed in the image below, what would be the simplest way to bring this into Rattlesnake? Can you provide an example? 

This may be out of the scope of Rattlesnake documentation but would be very useful to a new user. Thank you!!

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/15878567/224104046-bea105cb-c76e-4e42-a3ce-fec96793159a.png">

**Comment by dprohe** [comment]
Unfortunately, there isn't an easier way to import a specification than loading in these files.  Given that MIMO vibration specifications can be defined at many frequency lines for many channels (and the relationships between all channels at each frequency line must also be specified), the "enter breakpoints into a table" method for defining specifications would quickly become unmanageable for any reasonably-sized control problem.  Rattlesnake doesn't interpolate for you either, so you need to create a specification defined at every frequency line for every channel in your test (except frequency lines where the specification is zero).

It shouldn't be too hard to make a specification like this using Python or Matlab.  For example in NumPy, you can use the interpolation function for the frequency lines of interest.  Be sure to convert to log units before interpolating, otherwise the log-log scale plot will look curved.

Here's a little Python script I put together to interpolate breakpoints.  You may need to modify the frequency spacing and breakpoints and re-run it if you have different frequency spacing than 2 Hz.

```python
import numpy as np
import matplotlib.pyplot as plt

# Adjust breakpoints here as necessary
breakpoints = [
    (20,  0.0053),
    (150, 0.04),
    (800, 0.04),
    (2000,0.00644)]

frequency_resolution = 2 # Hz frequency spacing

breakpoints = np.array(breakpoints)
breakpoint_frequencies = breakpoints[:,0]

frequency_vector = np.arange(breakpoint_frequencies[0], # Start frequency
                             breakpoint_frequencies[-1]+frequency_resolution*0.0001, # Add just a bit to keep from truncating last frequency
                             frequency_resolution) # Frequency step

# Replicate the plot in the issue
plt.loglog(breakpoints[:,0],breakpoints[:,1])
plt.ylim(0.001,0.1)
plt.xlim(10,2000)

# Now we need to interpolate.  However, we need to interpolate on a log-log
# scale
log_frequency_vector = np.log(frequency_vector)
log_breakpoints = np.log(breakpoints)
log_specification = np.interp(log_frequency_vector,
                              log_breakpoints[:,0],
                              log_breakpoints[:,1])
specification = np.exp(log_specification)

plt.loglog(frequency_vector,specification,'r.')

# Note that we need to have specification be the right shape.
# Must be nf x nc x nc where nf is num frequency lines, nc is number of channels
# We will assume a single control channel here.
# CPSDs are also complex, so we will make it complex
specification = specification[:,np.newaxis,np.newaxis].astype(complex)

print('Specification Shape: {:}'.format(specification.shape))

# Save out something that Rattlesnake can use
np.savez('rattlesnake_specification.npz',f=frequency_vector,
         cpsd = specification)
```

I zipped up the output file and attached it here:
[rattlesnake_specification.zip](https://github.com/sandialabs/rattlesnake-vibration-controller/files/11013089/rattlesnake_specification.zip)

Hopefully this works for you.  Rattlesnake is meant at its heart to be a research code, so most of the time it provides the "most flexible" approach rather than the "easiest" or "most straightforward".

**Comment by kgrammatis** [comment]
Thank you for writing this up, I really appreciate it.  I just loaded it up and, wow, it looks like you created the spectra for me!! I'm so grateful!!

The control python script is beyond me. I loaded up buzz_psuedoinverse_control.py and had success, but without really understanding what all the different control laws do / how they work I'm not sure if that's the right choice. 

I understand what you mean by 'most flexible' - this tool is for experts. I'd expect nothing more from Sandia Labs 😊

For some context: I have an old shaker as well as some cDAQ's from other projects.  I thought to cobble together a vibe test system for a research project but the controller and accompanying software is prohibitively expensive. Your software, if I can figure it out, will solve a big problem for me.  There are probably others out there who could make use of this work. Used shakers are cheap, but the controllers are nowhere to be found for less than $20k. DIY / university / academic researchers would certainly love this. If you found the courage to include some functionality for the novice I'm sure it would be put to use!
